import { useEffect, useState } from 'react';
import { useConnection } from './network';
import { IslandBoard, type BuildMode } from './board/BoardLoader';
import { Arrival, Lobby, Brand } from './ui/Lobby';
import { Avatar } from './ui/Avatar';
import { ResourceIcon, LABELS } from './ui/Icons';
import { TradePanel, QuantityPicker } from './ui/TradePanel';
import { CardPanel } from './ui/CardPanel';
import { SettingsPanel, RulesPanel, HistoryPanel, type Settings } from './ui/Settings';
import { useAudio } from './audio/useAudio';
import { RESOURCES, emptyHand, countHand, type Action, type GameView } from '../../../packages/game-engine/src/types';
type Panel = 'trade' | 'cards' | 'settings' | 'history' | 'rules' | null;
const defaults: Settings = { master: .6, music: .25, effects: .65, ambient: .15, muted: false, quality: 'auto', reduced: 'system' };
function phaseText(game: GameView) { return ({ 'setup-settlement': 'PLACE YOUR SETTLEMENT', 'setup-road': 'CHOOSE YOUR ROAD', roll: 'A new turn. A new possibility.', discard: 'The Wanderer stirs. Discard excess cards.', robber: 'Find a new place for the Wanderer', victim: 'Choose a neighbor to take one card from', main: 'Build, trade, and find your way', 'free-roads': 'Place your free roads', over: 'An island. A story. A winner.' })[game.phase]; }
export function App() {
  const net = useConnection(), game = net.view?.game;
  const [settings, setSettings] = useState<Settings>(() => { try { return { ...defaults, ...JSON.parse(localStorage.getItem('morrow-settings') ?? '{}') }; } catch { return defaults; } });
  const [panel, setPanel] = useState<Panel>(null), [mode, setMode] = useState<BuildMode>(null), [reset, setReset] = useState(0), [handExpanded, setHandExpanded] = useState(false), [discards, setDiscards] = useState(emptyHand), [fullMessage, setFullMessage] = useState('');
  const [systemReduced, setSystemReduced] = useState(matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(() => { const media = matchMedia('(prefers-reduced-motion: reduce)'); const listener = () => setSystemReduced(media.matches); media.addEventListener('change', listener); return () => media.removeEventListener('change', listener); }, []);
  const motion = settings.reduced === 'system' ? !systemReduced : settings.reduced === 'off';
  useEffect(() => { localStorage.setItem('morrow-settings', JSON.stringify(settings)); }, [settings]);
  useEffect(() => { setMode(null); setDiscards(emptyHand()); }, [game?.phase, game?.active]);
  useAudio(game?.events ?? [], settings);
  const act = (action: Action) => { if (net.intro) return; net.act(action); if (action.type.startsWith('BUILD_')) setMode(null); };
  const fullscreen = async () => { try { if (!document.fullscreenElement) { if (document.documentElement.requestFullscreen) await document.documentElement.requestFullscreen(); else setFullMessage('This browser uses its normal landscape view. You can keep playing.'); } else await document.exitFullscreen(); } catch { setFullMessage('Full screen was declined. You can keep playing in this window.'); } };
  const open = (next: Panel) => { setMode(null); setPanel(panel === next ? null : next); };
  const myTurn = !!game && game.players[game.active].id === game.self.id, active = game?.players[game.active];
  const canMain = myTurn && game?.phase === 'main';
  const isSetup = game?.phase === 'setup-settlement' || game?.phase === 'setup-road';
  const tradeEvent = game?.events.filter(e => e.type === 'trade').at(-1);
  const lastEvent = game?.events.at(-1);
  const quality = settings.quality === 'auto' ? (navigator.hardwareConcurrency <= 4 || innerHeight < 550 ? 'low' : 'medium') : settings.quality;
  const intro = net.intro && motion && quality !== 'flat';
  useEffect(() => { if (net.intro && (!motion || quality === 'flat')) net.finishIntro(); }, [net.intro, motion, quality]);
  return <div className={`app ${game ? 'in-game' : 'pre-game'} ${motion ? '' : 'reduced-motion'} ${intro ? 'world-introducing' : ''} ${isSetup ? 'setup-phase' : ''}`} data-world-quality={quality} data-world-stage={intro ? 'arriving' : 'ready'}>
    <header className="topbar"><Brand/><div className="topbar-center">{game ? <><span className="turn-label">TURN {game.turn || 'SETUP'}</span><span>{active!.name}{myTurn ? ' · your turn' : ''}</span><button className="dice-readout" onClick={() => open('history')} aria-label="Dice history">{game.dice ? `${game.dice[0]} + ${game.dice[1]}` : '– + –'}<strong>{game.dice ? game.dice[0] + game.dice[1] : '–'}</strong></button></> : <span>YOUR NEXT GOOD EVENING STARTS HERE</span>}</div><div className="utilities"><span className={`connection ${net.online ? 'online' : ''}`}>{net.online ? 'Local table' : 'Connecting'}</span><button className="icon-button" aria-label="Rules and help" title="Rules and help" onClick={() => open('rules')}>?</button><button className="icon-button" aria-label="Settings" title="Settings" onClick={() => open('settings')}>☷</button><button className="icon-button full-button" aria-label="Enter full screen" title="Full screen" onClick={fullscreen}>⛶</button></div></header>
    {!game ? <main className="welcome"><div className="welcome-board"><IslandBoard preview motion={motion} quality={quality} reset={reset}/><div className="world-caption"><span className="eyebrow">CONQUEST OF PIZZERIA · EST. THIS EVENING</span><span>Every island begins with a little possibility.</span></div><div className="floating-note"><span>✦</span><div>A world of your own<small>Grown from scratch. Shared with friends.</small></div></div></div>{net.view ? <Lobby net={net}/> : <Arrival net={net}/>}</main> : <main className="match">
      <aside className="player-rail" aria-label="Players"><div className="eyebrow rail-heading">AROUND THE ISLE</div>{game.players.map((p, i) => <div className={`player ${i === game.active ? 'active-player' : ''} ${!p.connected && !p.ai ? 'disconnected' : ''} ${tradeEvent?.players.includes(p.id) ? 'trade-glow' : ''}`} key={`${p.id}-${tradeEvent?.players.includes(p.id) ? tradeEvent.id : 'steady'}`} style={{ '--player-color': p.color } as React.CSSProperties}><Avatar {...p} size={42}/><div className="player-info"><strong>{p.name}{p.id === game.self.id && <small> you</small>}</strong><span>{!p.connected && !p.ai ? 'Reconnecting…' : p.ai && i === game.active ? 'Considering…' : p.ai ? `${p.difficulty} companion` : `Seat ${i + 1}`}</span><div className="player-counts"><span title="Resource cards">▱ {p.resourceCount}</span><span title="Discovery cards">◇ {p.developmentCount}</span><span title="Played guards">♜ {p.guards}</span></div></div><span className="player-score" title="Public victory points">{p.score}<small>VP</small></span>{(game.longestRoad === p.id || game.largestGuard === p.id) && <span className="award-badge">{game.longestRoad === p.id ? '⌁ Longest Trail' : ''}{game.largestGuard === p.id ? ' ♜ Island Watch' : ''}</span>}</div>)}<div className="target-note"><span>✦</span><strong>{game.target} points</strong><small>A little ambition goes a long way.</small></div></aside>
      <div className="game-board"><IslandBoard game={game} mode={mode} act={act} motion={motion} quality={quality} reset={reset} intro={intro} onIntroComplete={net.finishIntro}/></div>
      {intro && <div className="world-intro" role="status"><span className="eyebrow">A LITTLE WORLD IS WAKING</span><h2>A new island. Your story.</h2><button onClick={net.finishIntro}>Skip arrival <span>→</span></button></div>}
      <div className="phase-banner"><span className={`phase-dot ${myTurn ? 'yours' : ''}`}/><div><strong>{isSetup && myTurn ? phaseText(game) : game.phase === 'over' ? `${game.players.find(p => p.id === game.winner)!.name} wins!` : myTurn ? 'Your move' : `${active!.name}'s move`}</strong>{(!isSetup || !myTurn) && <span>{phaseText(game)}</span>}</div>{net.busy && <small>Sending…</small>}</div>
      <aside className="action-rail" aria-label="Game actions"><div className="eyebrow">MAKE YOUR MOVE</div>{game.phase === 'roll' && <button className="primary roll-button" disabled={!myTurn || net.busy || !net.online} onClick={() => act({ type: 'ROLL_DICE' })}><span>⚄</span>Roll dice</button>}<button className={mode ? 'selected secondary' : 'secondary'} disabled={!canMain || net.busy} onClick={() => { setPanel(null); setMode(mode ? null : 'road'); }}><span>⌂</span>Build</button><button className={`secondary ${game.trade ? 'has-offer' : ''}`} disabled={game.phase !== 'main'} onClick={() => open('trade')}><span>⇄</span>{game.trade ? 'Trade offer' : 'Trade'}</button><button className="secondary" onClick={() => open('cards')}><span>◇</span>Discoveries<small>{game.self.cards.length}</small></button><button className="end-turn" disabled={!canMain || net.busy || !net.online} onClick={() => { setPanel(null); act({ type: 'END_TURN' }); }}>End turn <span>→</span></button><div className="action-utilities"><button className="text-button" onClick={() => setReset(r => r + 1)}>↺ Reset view</button><button className="text-button" onClick={() => open('history')}>Rolls & journal</button></div></aside>
      {mode && <div className="build-tray"><span>BUILD SOMETHING LASTING</span>{(['road', 'settlement', 'city'] as const).map(m => <button key={m} className={mode === m ? 'selected' : ''} onClick={() => setMode(m)}><b>{m === 'road' ? 'Road' : m === 'city' ? 'City' : 'Settlement'}</b><small>{m === 'road' ? '1 WOOD · 1 BRICK' : m === 'settlement' ? '1 WOOD · 1 BRICK · 1 GRAIN · 1 WOOL' : '2 GRAIN · 3 ORE'}</small><em>{(m === 'road' ? game.legal.roads : m === 'city' ? game.legal.cities : game.legal.settlements).length} legal sites</em></button>)}<button className="icon-button" aria-label="Close build menu" onClick={() => setMode(null)}>×</button></div>}
      {game.phase === 'victim' && myTurn && <div className="victim-tray"><strong>Choose a neighbor</strong>{game.legal.victims.map(id => { const p = game.players.find(p => p.id === id)!; return <button disabled={net.busy} className="secondary" key={id} onClick={() => act({ type: 'STEAL', victim: id })}><Avatar {...p} size={30}/>{p.name}</button>; })}</div>}
      <div className="table-event" aria-live="polite" key={lastEvent?.id}>{lastEvent?.text ?? 'The island is yours to explore.'}</div>
      <footer className={`hand-dock ${handExpanded ? 'expanded' : ''}`}><button className="hand-heading" onClick={() => setHandExpanded(!handExpanded)} aria-expanded={handExpanded}><span className="eyebrow">YOUR HAND <span className="lock-icon">♧</span></span><strong>{countHand(game.self.resources)} cards <small>· only you can see these</small></strong><span className="tray-toggle">{handExpanded ? '⌄' : '⌃'}</span></button><div className="resource-hand">{RESOURCES.map(r => <div className={`resource-card ${r}`} key={r}><ResourceIcon resource={r} size={31}/><span>{LABELS[r]}</span><b>{game.self.resources[r]}</b></div>)}</div><div className="private-score"><strong>{game.self.score}<small> / {game.target}</small></strong><span>YOUR VICTORY POINTS</span></div></footer>
      {game.phase === 'over' && <div className="victory-card"><div className="eyebrow">A STORY WORTH SHARING</div><h1>{game.players.find(p => p.id === game.winner)!.name}'s island.</h1><p>Every road, every deal, every little possibility led here.</p><button className="primary" onClick={() => open('history')}>See the story in numbers</button><button className="text-button" onClick={() => { localStorage.removeItem('morrow-session'); location.href = location.pathname; }}>Gather for a new island →</button></div>}
    </main>}
    {(panel || (game && game.discards[game.self.id])) && <aside className="side-sheet" aria-label={game?.discards[game.self.id] ? 'Discard resources' : `${panel} panel`}><button className="icon-button sheet-close" aria-label="Close panel" onClick={() => setPanel(null)}>×</button>{game?.discards[game.self.id] ? <><div className="eyebrow">THE WANDERER STIRS</div><h2>Travel a little lighter.</h2><p>Discard exactly {game.discards[game.self.id]} resource cards.</p><QuantityPicker title="Discard" value={discards} setValue={setDiscards} max={game.self.resources}/><button className="primary wide" disabled={net.busy || countHand(discards) !== game.discards[game.self.id]} onClick={() => act({ type: 'DISCARD', cards: discards })}>Discard {countHand(discards)} / {game.discards[game.self.id]}</button></> : <>{panel === 'trade' && game && <TradePanel game={game} act={act} busy={net.busy}/ >}{panel === 'cards' && game && <CardPanel game={game} act={act} busy={net.busy}/ >}{panel === 'history' && game && <HistoryPanel game={game}/ >}{panel === 'rules' && <RulesPanel shiftingPorts={game?.settings.shiftingPorts ?? net.view?.lobby.settings.shiftingPorts} locked={!!game}/>}{panel === 'settings' && <SettingsPanel settings={settings} setSettings={setSettings} reset={() => setReset(r => r + 1)} fullscreen={fullscreen} leave={net.view ? () => { localStorage.removeItem('morrow-session'); location.href = location.pathname; } : undefined}/>}</>}</aside>}
    {(net.error || fullMessage) && <div className="toast" role="alert"><span>{net.error || fullMessage}</span><button aria-label="Dismiss message" onClick={() => { net.clearError(); setFullMessage(''); }}>×</button></div>}
    {game && !net.online && <div className="connection-banner">Connection paused. Keep this page open; your seat will return when the host is reachable.</div>}
    {game && <div className="rotate-screen"><Brand/><div className="rotate-icon">▯ ↻</div><h1>A wider world awaits.</h1><p>Rotate your phone to landscape.<br/>Your place at the table is saved.</p><small>CONQUEST OF PIZZERIA</small></div>}
  </div>;
}
