import { useState } from 'react';
import { RESOURCES, type GameView, type Resource, type Action, type CardKind } from '../../../../packages/game-engine/src/types';
import { CARD_NAMES } from '../../../../packages/game-engine/src/development';
import { LABELS, ResourceIcon } from './Icons';
const descriptions: Record<CardKind, string> = { guard: 'Move the Wanderer and take one random card from a neighbor. Three guards can earn the Island Watch.', charter: 'One hidden victory point. It counts automatically on your turn.', roads: 'Place up to two legal roads at no resource cost.', harvest: 'Take any two resource cards available in the bank.', monopoly: 'Name a resource. Every other player gives you all cards of that kind.' };
export function CardPanel({ game, act, busy }: { game: GameView; act: (a: Action) => void; busy: boolean }) {
  const [one, setOne] = useState<Resource>('ore'), [two, setTwo] = useState<Resource>('grain');
  return <><h2>Little discoveries</h2><p className="quiet">One playable card each turn. New cards rest until your next turn. Charters count automatically.</p>
    <button className="secondary wide" disabled={busy || !game.legal.canBuyCard} onClick={() => act({ type: 'BUY_CARD' })}>Draw a discovery · {game.deckCount} left</button><p className="card-cost">Cost: <ResourceIcon resource="wool" size={18}/><ResourceIcon resource="grain" size={18}/><ResourceIcon resource="ore" size={18}/></p>
    {game.self.cards.length === 0 && <div className="empty-state">Something unexpected awaits.<br/><small>Build your discovery collection here.</small></div>}
    {[...new Set(game.self.cards.map(c => c.kind))].map(kind => <article className="discovery" key={kind}><div className="discovery-mark">{({ guard: '♜', charter: '✦', roads: '⌁', harvest: '❋', monopoly: '◇' })[kind]}</div><h3>{CARD_NAMES[kind]} <small>×{game.self.cards.filter(c => c.kind === kind).length}</small></h3><p>{descriptions[kind]}</p>{kind === 'harvest' || kind === 'monopoly' ? <div className="button-row"><select aria-label={`${kind} first resource`} value={one} onChange={e => setOne(e.target.value as Resource)}>{RESOURCES.map(r => <option value={r} key={r}>{LABELS[r]}</option>)}</select>{kind === 'harvest' && <select aria-label="Harvest second resource" value={two} onChange={e => setTwo(e.target.value as Resource)}>{RESOURCES.map(r => <option value={r} key={r}>{LABELS[r]}</option>)}</select>}</div> : null}{kind !== 'charter' && <button className="text-button" disabled={busy || !game.legal.playableCards.includes(kind)} onClick={() => act({ type: 'PLAY_CARD', kind, resources: kind === 'harvest' ? [one, two] : kind === 'monopoly' ? [one] : undefined })}>{game.legal.playableCards.includes(kind) ? 'Play this discovery →' : 'Resting until a later turn'}</button>}</article>)}
  </>;
}
