import type { GameView } from '../../../../packages/game-engine/src/types';
import type { AudioSettings } from '../audio/useAudio';
export interface Settings extends AudioSettings { quality: string; reduced: 'system' | 'on' | 'off' }
export function SettingsPanel({ settings, setSettings, reset, fullscreen, leave }: { settings: Settings; setSettings: (s: Settings) => void; reset: () => void; fullscreen: () => void; leave?: () => void }) {
  return <><h2>Make yourself at home</h2><label className="setting">Sound<button className="secondary" aria-label={settings.muted ? 'Unmute audio' : 'Mute audio'} onClick={() => setSettings({ ...settings, muted: !settings.muted })}>{settings.muted ? 'Unmute' : 'Mute'}</button></label>{(['master', 'music', 'effects', 'ambient'] as const).map(key => <label className="setting" key={key}>{key}<input aria-label={`${key} volume`} type="range" min="0" max="1" step=".05" value={settings[key]} onChange={e => setSettings({ ...settings, [key]: +e.target.value })}/></label>)}<label className="setting">Graphics<select value={settings.quality} onChange={e => setSettings({ ...settings, quality: e.target.value })}><option value="auto">Auto</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="flat">Flat board fallback</option></select></label><label className="setting">Reduce motion<select value={settings.reduced} onChange={e => setSettings({ ...settings, reduced: e.target.value as Settings['reduced'] })}><option value="system">Follow device</option><option value="on">On</option><option value="off">Off</option></select></label><button className="secondary wide" onClick={reset}>Reset camera</button><button className="secondary wide" onClick={fullscreen}>Enter full screen</button><p className="quiet">Settings stay in this browser. Full screen is optional; if your browser declines, gameplay continues.</p>{leave && <><button className="text-button" onClick={leave}>Return to welcome →</button><p className="quiet">Your seat stays reserved. Reopen the island's join link in this browser to return.</p></>}</>;
}
export function HistoryPanel({ game }: { game: GameView }) {
  const sums = game.history.map(d => d[0] + d[1]);
  return <><h2>Every roll, as it happened</h2><p className="quiet">Two independent dice. No balancing, correction, or memory. Past rolls never change the next one.</p><div className="history-rolls">{sums.length ? sums.slice(-60).map((n, i) => <span key={i}>{n}</span>) : 'The first roll is still to come.'}</div><p>{sums.length} rolls this game</p><div className="histogram">{Array.from({ length: 11 }, (_, i) => i + 2).map(n => { const count = sums.filter(s => s === n).length, percent = sums.length ? count * 100 / sums.length : 0; return <div key={n}><b>{n}</b><span><i style={{ width: `${percent * 3}%` }}/></span><small>{count} · {percent.toFixed(1)}%</small></div>; })}</div><h3>Around the table</h3><ol className="event-log">{[...game.events].reverse().map(e => <li key={e.id}>{e.text}</li>)}</ol></>;
}
export function RulesPanel({ shiftingPorts, locked = false }: { shiftingPorts?: boolean; locked?: boolean }) { return <><h2>Your first evening on the isle</h2><p>Reach the victory target on your turn. Settlements earn 1 point, cities 2. The Longest Trail and Island Watch awards earn 2 each. Charter cards are hidden points.</p><h3>Make a beginning</h3><p>Place a settlement and an adjoining road. Everyone places once, then again in reverse order. Your second settlement collects one resource from each neighboring productive tile.</p><h3>Roll, gather, build</h3><p>Roll two dice at the start of your turn. Matching tiles give adjacent settlements 1 resource and cities 2. If the bank cannot cover all claims for one resource, it supplies none of that resource.</p><ul><li>Road: 1 WOOD + 1 BRICK.</li><li>Settlement: 1 WOOD + 1 BRICK + 1 GRAIN + 1 WOOL.</li><li>City: 2 GRAIN + 3 ORE.</li><li>Discovery: 1 GRAIN + 1 WOOL + 1 ORE.</li></ul><p>Settlements must be at least two edges apart and connect to your roads after setup. Opposing buildings interrupt road connections.</p><h3>The Wanderer</h3><p>On a 7, everyone holding more than 7 resources discards half, rounded down. Then move the Wanderer to a different tile and select an eligible neighbor to take one random card. Its tile produces nothing while blocked. Blocked production never removes cards already in a hand.</p><h3>Shifting Ports{shiftingPorts !== undefined && (shiftingPorts ? ' · ON' : ' · OFF')}{locked && ' · Locked'}</h3><p>{shiftingPorts === false ? 'Ports remain fixed for this match. Rolling 7 uses the classic discard, Wanderer move and theft sequence.' : 'After a rolled 7, finish all discards, move the Wanderer and complete any theft. Then the existing port types exchange legal coastal docks. Port counts stay the same; trade rates update immediately. Playing a Guard does not move ports.'} {locked ? 'The host selected this rule before the match.' : 'The host can switch this rule off in the lobby.'}</p><h3>Make a deal</h3><p>The active player proposes an exchange. Others accept, counter or pass. The active player confirms one response. Bank trading is 4:1; owned ports improve it to 3:1 or 2:1 for their named resource.</p><h3>Discoveries & awards</h3><p>Play at most one discovery per turn, before or after rolling. Newly bought cards wait until a later turn. Charters count automatically. Five connected roads can claim Longest Trail; three guards can claim Island Watch. A tied holder keeps an award; a strictly higher challenger takes it.</p><h3>A bigger gathering</h3><p>Expanded and Grand use larger boards, banks and decks. Grand is Conquest of Pizzeria's custom 7–8 player extension. Turns remain sequential. These large boards are experimental and need human balance playtesting.</p><p className="quiet">Keep the host running. Refreshing restores your seat in the same browser. Host shutdown ends in-memory sessions.</p></>; }
