import { useEffect, useState } from 'react';
import { RESOURCES, emptyHand, countHand, type Hand, type GameView, type Resource, type Action } from '../../../../packages/game-engine/src/types';
import { canAfford } from '../../../../packages/game-engine/src/economy';
import { ResourceIcon, LABELS } from './Icons';
export function QuantityPicker({ value, setValue, max, title }: { value: Hand; setValue: (h: Hand) => void; max?: Hand; title: string }) {
  return <fieldset className="quantity-picker"><legend>{title}</legend>{RESOURCES.map(r => <div key={r}><span className={`resource-color ${r}`}><ResourceIcon resource={r} size={19}/>{LABELS[r]}</span><button aria-label={`Less ${LABELS[r]} ${title}`} disabled={!value[r]} onClick={() => setValue({ ...value, [r]: value[r] - 1 })}>−</button><output>{value[r]}</output><button aria-label={`More ${LABELS[r]} ${title}`} disabled={value[r] >= (max?.[r] ?? 19)} onClick={() => setValue({ ...value, [r]: value[r] + 1 })}>＋</button></div>)}</fieldset>;
}
export function Terms({ hand }: { hand: Hand }) { return <span className="terms">{RESOURCES.filter(r => hand[r]).map(r => <span key={r} title={LABELS[r]}><ResourceIcon resource={r} size={19}/>{hand[r]} <small>{LABELS[r]}</small></span>)}</span>; }
export function TradePanel({ game, act, busy }: { game: GameView; act: (a: Action) => void; busy: boolean }) {
  const [tab, setTab] = useState<'players' | 'bank'>('players'), [give, setGive] = useState(emptyHand), [want, setWant] = useState(emptyHand), [bankGive, setBankGive] = useState<Resource>('wood'), [bankWant, setBankWant] = useState<Resource>('ore'), [counter, setCounter] = useState(false), [confirm, setConfirm] = useState<string | null>(null);
  const me = game.self.id, active = game.players[game.active].id === me, trade = game.trade;
  const response = trade?.responses.find(r => r.player === confirm);
  useEffect(() => { setConfirm(null); setCounter(false); setTab('players'); }, [trade?.id]);
  const valid = countHand(give) > 0 && countHand(want) > 0 && canAfford(game.self.resources, give) && !RESOURCES.some(r => give[r] && want[r]);
  return <><h2>A fair exchange</h2><p className="quiet">A good deal moves both of you forward.</p><div className="segmented"><button className={tab === 'players' ? 'selected' : ''} onClick={() => setTab('players')}>With players</button><button className={tab === 'bank' ? 'selected' : ''} onClick={() => setTab('bank')}>Bank & ports</button></div>
    {tab === 'bank' ? <div className="bank-panel"><label>You give<select value={bankGive} onChange={e => setBankGive(e.target.value as Resource)}>{RESOURCES.map(r => <option key={r} value={r}>{game.legal.bankRatios[r]} {LABELS[r]}</option>)}</select></label><div className="exchange-symbol">⇄</div><label>You receive<select value={bankWant} onChange={e => setBankWant(e.target.value as Resource)}>{RESOURCES.map(r => <option key={r} value={r}>1 {LABELS[r]} · {game.bank[r]} in bank</option>)}</select></label><p className="quiet">Your coastal ports automatically apply the best rate.</p><button className="primary wide" disabled={busy || !active || game.phase !== 'main' || bankGive === bankWant || game.self.resources[bankGive] < game.legal.bankRatios[bankGive] || game.bank[bankWant] < 1} onClick={() => act({ type: 'BANK_TRADE', give: bankGive, want: bankWant })}>Exchange {game.legal.bankRatios[bankGive]}:1</button></div> : <>
      {trade && <div className="offer-summary"><div className="eyebrow">{game.players.find(p => p.id === trade.owner)!.name}'S OFFER</div><p><Terms hand={trade.give}/><span className="exchange-symbol">⇄</span><Terms hand={trade.want}/></p></div>}
      {trade && trade.owner !== me && !counter && <><div className="trade-confirm"><span>YOU GIVE</span><Terms hand={trade.want}/><span>YOU RECEIVE</span><Terms hand={trade.give}/></div><div className="button-row"><button className="primary" disabled={busy || !canAfford(game.self.resources, trade.want)} onClick={() => act({ type: 'RESPOND_TRADE', tradeId: trade.id, response: 'accept', give: emptyHand(), want: emptyHand() })}>Accept terms</button><button className="secondary" onClick={() => { setCounter(true); setGive(trade.want); setWant(trade.give); }}>Counter</button><button className="text-button" disabled={busy} onClick={() => act({ type: 'RESPOND_TRADE', tradeId: trade.id, response: 'pass', give: emptyHand(), want: emptyHand() })}>Pass</button></div>{trade.responses.some(r => r.player === me) && <p className="quiet">Your response is on the table. The active player confirms the final exchange.</p>}</>}
      {trade?.owner === me && <div className="trade-responses">{!trade.responses.length && <p className="quiet">Your offer is on the table. Waiting for replies…</p>}{trade.responses.map(r => <button key={r.player} className="response-card" disabled={r.status === 'pass'} onClick={() => setConfirm(r.player)}><strong>{game.players.find(p => p.id === r.player)!.name}<small>{r.status}</small></strong>{r.status !== 'pass' && <><Terms hand={r.give}/><span>for</span><Terms hand={r.want}/></>}</button>)}{response && <div className="trade-confirm"><b>Confirm your exchange</b><span>YOU GIVE</span><Terms hand={response.want}/><span>YOU RECEIVE</span><Terms hand={response.give}/><button className="primary wide" disabled={busy || !canAfford(game.self.resources, response.want)} onClick={() => act({ type: 'CONFIRM_TRADE', tradeId: trade.id, player: response.player })}>Confirm exchange</button></div>}<button className="text-button" disabled={busy} onClick={() => act({ type: 'CANCEL_TRADE' })}>Withdraw offer</button></div>}
      {(!trade || counter) && (active || counter) && <><QuantityPicker title="You give" value={give} setValue={setGive} max={game.self.resources}/><QuantityPicker title="You want" value={want} setValue={setWant}/><button className="primary wide" disabled={busy || !valid || game.phase !== 'main'} onClick={() => { if (counter && trade) { act({ type: 'RESPOND_TRADE', tradeId: trade.id, response: 'counter', give, want }); setCounter(false); } else act({ type: 'PROPOSE_TRADE', give, want }); }}>{counter ? 'Send counteroffer' : 'Put an offer on the table'}</button></>}
      {!trade && !active && <p>Only the active player can open a trade. Incoming offers will appear here.</p>}
    </>}
  </>;
}
